controllers:
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

